### ISSUE TITLE
User data or application data?

### ISSUE THREAD

**Issue by Heath123** [minosvasilias/toolformer-zero#5]
The page says:
> If no API key is listed under "API keys", create a new one  by pressing "+ Create Credentials" and then "API key" at the top, then copy the generated API key

Am I on the right page here? If so, which one of these do I select?
![3625A9DE-48ED-445E-A3C6-F9EFD64861B7](https://user-images.githubusercontent.com/13787163/220150086-56bad34c-df8e-49a4-9113-48d8f644e882.jpeg)

**Comment by Heath123** [comment]
I would guess “Application data” but then it wants to create a service account which that page doesn’t mention so that makes me think that’s not right, but then “User data” wants me to set up an “OAuth Consent Screen which also isn’t mentioned. Am I in the wrong place entirely?

**Comment by minosvasilias** [comment]
Hey! Judging by your screenshot, am i right in assuming you are on mobile? 
Unfortunately i didn't really consider mobile when writing the instructions, so it might be easier to do on desktop if possible.

There, you should find the following page after following the link in the setup and enabling the API:
<img width="1440" alt="Screenshot 2023-02-20 at 17 00 15" src="https://user-images.githubusercontent.com/44006014/220153624-7cd92e53-d266-4d53-855c-394696c61859.png">

If you got that, do not click on the `Credentials` tab next to `Metrics` and `Quotas`, but instead the `Credentials` button in the menu on the left.
There you should find: 
<img width="1440" alt="Screenshot 2023-02-20 at 16 59 52" src="https://user-images.githubusercontent.com/44006014/220153877-d2d88a7b-e9a2-4e1d-b820-e4c584320a6d.png">

where pressing on `API key` should generate a key without any further steps at all.

Let me know if that helps. I might look at how to improve the experience of this on mobile, which admittedly is pretty bad at the moment.

**Comment by Heath123** [comment]
Thanks, I will do this in 10 minutes or so when I get home, I just assumed that that mobile UI would be roughly the same but maybe not

**Comment by Heath123** [comment]
Using the desktop version works, thanks
